### ISSUE TITLE
stacksort cannot get data!

### ISSUE THREAD

**Issue by nootanghimire** [gkoberger/stacksort#16]
Cross Origin Request is Blocked in my firefox! Is this beacause Stackoverflow stopped enabling CORS? 
or maybe it's wiser now to use JSONP now?

**Comment by gkoberger** [comment]
Should be working now; let me know if it isn't.

**Comment by nootanghimire** [comment]
![shot-2015-01-24_23-17-38](https://cloud.githubusercontent.com/assets/2210043/5888261/c7854ef6-a41f-11e4-8803-98015b353720.png)
Still No! :disappointed:

**Comment by gkoberger** [comment]
@nootanghimire Ah, you can't make AJAX calls from localhost. You'll have to run it as a server for it to work.

So, inside the main stacksort directory (and assuming you have Python installed), do this:

    python -m SimpleHTTPServer 8000

Then, go to http://localhost:8000

Let me know if this doesn't work!

**Comment by nootanghimire** [comment]
@gkoberger  : Same happens when opening from your github link: http://gkoberger.github.io/stacksort/ and same using local python server.
![shot-2015-01-25_18-45-15](https://cloud.githubusercontent.com/assets/2210043/5891524/243a3938-a4c3-11e4-8112-5d3409f97401.png)
