### ISSUE TITLE
Doesn't work in HTTPS

### ISSUE THREAD

**Issue by tuxayo** [gkoberger/stacksort#20]
Firefox:
Blocked loading mixed active content "http://api.stackexchange.com/2.1/questions?sort=activity&tagged=sort;javascript&page=1&pagesize=100&order=desc&site=stackoverflow&todate=1363060800"[Learn More]

Chromium:
Mixed Content: The page at 'https://gkoberger.github.io/stacksort/?' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://api.stackexchange.com/2.1/questions?sort=activity&tagged=sort;javascript&page=1&pagesize=100&order=desc&site=stackoverflow&todate=1363060800'. This request has been blocked; the content must be served over HTTPS.send @ jquery.js:5

**Comment by gkoberger** [comment]
Seems like this was fixed!
